[package]
name = "bar-gui"
description = "Node-based editor GUI built on egui"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
bar-data = { workspace = true }
bar-graph = { workspace = true }
bar-project = { workspace = true }
egui = { workspace = true }
eframe = { workspace = true }
rfd = { workspace = true }
raw-window-handle = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
directories = { workspace = true }
image = { workspace = true }
include_dir = { workspace = true }

[dev-dependencies]
