//! Layer definitions for export targets.

use super::dimensions::DimensionRule;

/// Format for a layer's pixel data.
#[derive(Debug, Clone, Copy, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum LayerFormat {
    /// 16-bit unsigned integer (heightmap).
    U16,
    /// 8-bit unsigned integer (metalmap, typemap, grassmap).
    U8,
    /// 32-bit float (internal processing format).
    F32,
    /// DXT1 compressed (minimap, tiles).
    Dxt1,
    /// RGBA 8-bit per channel (diffuse texture).
    Rgba8,
    /// RGB 8-bit per channel (normal maps).
    Rgb8,
}

/// Whether a layer is required, optional, or unsupported by a target.
#[derive(Debug, Clone, Copy, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum LayerStatus {
    /// Layer must be present for a valid export.
    Required,
    /// Layer is written if available, skipped otherwise.
    Optional,
    /// Layer is not supported by this target (error if provided).
    Unsupported,
    /// Layer is auto-generated by the codec (e.g., minimap from heightmap).
    Generated,
}

/// A layer requirement defined by a target.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct LayerRequirement {
    /// Layer identifier (e.g., "heightmap", "metalmap", "normalmap").
    pub name: String,
    /// Required data format.
    pub format: LayerFormat,
    /// How to compute this layer's dimensions.
    pub resolution: DimensionRule,
    /// Whether this layer is required/optional/generated.
    pub status: LayerStatus,
}

/// A collection of computed layer data ready for export.
#[derive(Debug, Default)]
pub struct LayerSet {
    pub heightmap: Option<bar_data::Heightmap>,
    pub metalmap: Option<bar_data::Heightmap>,
    pub typemap: Option<bar_data::Heightmap>,
    pub grassmap: Option<bar_data::Heightmap>,
    pub normalmap: Option<bar_data::ColorBuffer>,
    pub texture: Option<bar_data::ColorBuffer>,
    pub specular: Option<bar_data::ColorBuffer>,
}

impl LayerSet {
    /// Check if a named layer is available.
    pub fn has_layer(&self, name: &str) -> bool {
        match name {
            "heightmap" => self.heightmap.is_some(),
            "metalmap" => self.metalmap.is_some(),
            "typemap" => self.typemap.is_some(),
            "grassmap" => self.grassmap.is_some(),
            "normalmap" => self.normalmap.is_some(),
            "texture" => self.texture.is_some(),
            "specular" => self.specular.is_some(),
            _ => false,
        }
    }
}
